blank_issues_enabled: true
contact_links:
  - name: Daily Report
    about: 日報のテンプレート
    url: https://github.com/{REPO}/issues/new?template=daily_report.md&projects={ORGANIZATION OR REPO}/Daily Report&labels=TODAY 
