name: Create Daily Report

on:
  schedule:
    - cron: '15 5 * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write 

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          assignees: "Yuma-Tsukakoshi"
          pinned: false
          close-previous: true
          filename: .github/ISSUE_TEMPLATE/daily_report.md
